version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mydb:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mydb:
    driver: local
    driver_opts:
      type: none
      device: /Users/izail/mydb
      o: bind
networks:
  inception_net: