version: '3.7'
services:
####################### NGINX #######################
  nginx:
    image: nginx
    container_name: nginx
    build : ./requirements/nginx/
    restart: on-failure
    env_file:
      - .env
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - my_wordpress:/var/www/html
    networks:
      - inceptionNet
####################### ADMINER #######################
  adminer:
    image: adminer
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - inceptionNet
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    restart: on-failure
####################### MARIADB #######################
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file: 
      - .env
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - my_database:/var/lib/mysql
    networks:
      - inceptionNet
####################### WORDPRESS #######################
  wordpress:
    image: wordpress
    container_name: wordpress
    build : ./requirements/wordpress/
    restart: always
    env_file:
      - .env
    ports:
      - 9000:9000
    depends_on:
      - mariadb
      - redis
    volumes:
      - my_wordpress:/var/www/html
    networks:
      - inceptionNet
####################### REDIS #######################
  redis:
    image: redis
    container_name: redis
    build: ./requirements/bonus/redis/
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - inceptionNet
####################### FTP #######################
  # ftp:
  #   image: ftp
  #   container_name: ftp
  #   build: ./requirements/bonus/ftp/
  #   restart: on-failure
  #   env_file:
  #     - .env
  #   ports:
  #     - "21:21"
  #   networks:
  #     - inceptionNet
####################### VOLUMES #######################
volumes:
  my_database:
    driver: local
    driver_opts:
      type: none
      device: /Users/izail/data/my_database
      o: bind
  my_wordpress :
    driver : local
    driver_opts:
      type : none
      device: /Users/izail/data/my_wordpress
      o: bind
####################### NETWORKS #######################
networks:
  inceptionNet:
      driver: bridge