version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    build : ./requirements/nginx/
    restart: on-failure
    env_file:
      - .env
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - my_wordpress:/var/www/html
    networks:
      - inceptionNet
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file: 
      - .env
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - my_database:/var/lib/mysql
    networks:
      - inceptionNet
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - inceptionNet
  wordpress:
    image: wordpress
    container_name: wordpress
    build : ./requirements/wordpress/
    restart: always
    env_file:
      - .env
    ports:
      - 9000:9000
    depends_on:
      - mariadb
      - redis
    volumes:
      - my_wordpress:/var/www/html
    networks:
      - inceptionNet
  redis:
    image: redis
    container_name: redis
    build: ./requirements/bonus/redis/
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - inceptionNet
volumes:
  my_database:
    driver: local
    driver_opts:
      type: none
      device: /Users/izail/data/my_database
      o: bind
  my_wordpress :
    driver : local
    driver_opts:
      type : none
      device: /Users/izail/data/my_wordpress
      o: bind
networks:
  inceptionNet:
      driver: bridge