CREATE DATABASE IF NOT EXISTS izail_db;
CREATE USER IF NOT EXISTS 'izail'@'%' IDENTIFIED BY 'izail1337';
GRANT ALL PRIVILEGES ON izail_db.* TO 'izail'@'%';
FLUSH PRIVILEGES;
-- ALTER USER 'root'@'%' IDENTIFIED BY 'root1337';