CREATE DATABASE IF NOT EXISTS ${DB_NAME};
CREATE USER IF NOT EXISTS ${DB_USER_NAME} IDENTIFIED BY ${DB_USER_PASS};
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO ${DB_USER_NAME};
FLUSH PRIVILEGES;
ALTER USER ${DB_ADMIN_NAME}@${HOST} IDENTIFIED BY ${DB_ADMIN_PASS};