CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'izail'@'%' IDENTIFIED BY 'izail1337';
GRANT ALL PRIVILEGES ON wordpress.* TO 'izail'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root1337';
FLUSH PRIVILEGES;